// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTY_2YqRoJFTbOoI-mUP95iJ3shZukKk',
    appId: '1:633168368670:web:6e57c5585f84b2117c8a0f',
    messagingSenderId: '633168368670',
    projectId: 'sdcampus-d00f3',
    authDomain: 'sdcampus-d00f3.firebaseapp.com',
    databaseURL: 'https://sdcampus-d00f3-default-rtdb.firebaseio.com',
    storageBucket: 'sdcampus-d00f3.firebasestorage.app',
    measurementId: 'G-FLTJDD23NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdAqL59EQHzcrCbj3up4_C0zqGMR1nekI',
    appId: '1:633168368670:android:b29cb9ce561b39a87c8a0f',
    messagingSenderId: '633168368670',
    projectId: 'sdcampus-d00f3',
    databaseURL: 'https://sdcampus-d00f3-default-rtdb.firebaseio.com',
    storageBucket: 'sdcampus-d00f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUgUVwahLgNeJNFnwwYa29X4DP-k6i8Y',
    appId: '1:633168368670:ios:5f1f8a082b0f86ea7c8a0f',
    messagingSenderId: '633168368670',
    projectId: 'sdcampus-d00f3',
    databaseURL: 'https://sdcampus-d00f3-default-rtdb.firebaseio.com',
    storageBucket: 'sdcampus-d00f3.firebasestorage.app',
    androidClientId: '633168368670-1vlsofh2kgbo3p9odr9ppaqh5q6onhpn.apps.googleusercontent.com',
    iosClientId: '633168368670-6uaq0q5a36233g8s6a30evu8lvamc5sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfUgUVwahLgNeJNFnwwYa29X4DP-k6i8Y',
    appId: '1:633168368670:ios:5f1f8a082b0f86ea7c8a0f',
    messagingSenderId: '633168368670',
    projectId: 'sdcampus-d00f3',
    databaseURL: 'https://sdcampus-d00f3-default-rtdb.firebaseio.com',
    storageBucket: 'sdcampus-d00f3.firebasestorage.app',
    androidClientId: '633168368670-1vlsofh2kgbo3p9odr9ppaqh5q6onhpn.apps.googleusercontent.com',
    iosClientId: '633168368670-6uaq0q5a36233g8s6a30evu8lvamc5sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoTY_2YqRoJFTbOoI-mUP95iJ3shZukKk',
    appId: '1:633168368670:web:4c8aeccca34b9de47c8a0f',
    messagingSenderId: '633168368670',
    projectId: 'sdcampus-d00f3',
    authDomain: 'sdcampus-d00f3.firebaseapp.com',
    databaseURL: 'https://sdcampus-d00f3-default-rtdb.firebaseio.com',
    storageBucket: 'sdcampus-d00f3.firebasestorage.app',
    measurementId: 'G-4V1D01J3TM',
  );

}